# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 02:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wanzi', '0004_auto_20160227_1013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 27, 2, 15, 2, 193806, tzinfo=utc)),
        ),
    ]
