# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 07:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wanzi', '0005_auto_20160227_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=' '),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 27, 7, 16, 16, 579113, tzinfo=utc)),
        ),
    ]
