# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 08:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wanzi', '0007_auto_20160227_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 27, 8, 2, 9, 278714, tzinfo=utc)),
        ),
    ]
