# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 08:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wanzi', '0008_auto_20160227_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 27, 8, 30, 22, 48192, tzinfo=utc)),
        ),
    ]
