# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 09:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wanzi', '0009_auto_20160227_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 27, 9, 16, 10, 124461, tzinfo=utc)),
        ),
    ]
